#!/usr/bin/env bash

BUILD_CMD="rebar3"
REBAR_CMD="./rebar3"
RELEASE_CMD="relx"
RELX_CMD="./rebar3"

# name of your release
APP="wocky"

# host where to build the release
BUILD_HOST="build1.dev.tinyrobot.com"

# local user at build host
BUILD_USER="ubuntu"

# build directory on build host
BUILD_AT="/home/ubuntu/wocky"

# Restart the node after deploying
START_DEPLOY=true


##
## STAGING / TEST
##

# staging / test hosts separated by space
STAGING_HOSTS="app1.dev.tinyrobot.com app2.dev.tinyrobot.com app3.dev.tinyrobot.com"

# local user at staging hosts
STAGING_USER="wocky"

# deploy directory on staging hosts. default is DELIVER_TO
TEST_AT="/opt"


##
## PRODUCTION
##

# deploy / production hosts separated by space
# Using this to deploy to the testing nodes since we don't have production
# nodes yet. Gonna have problems when we start deploying production
# environments.
PRODUCTION_HOSTS="test1.dev.tinyrobot.com"

# local user at deploy hosts
PRODUCTION_USER="wocky"

# deploy directory on production hosts
DELIVER_TO="/opt"
